version: "3"
services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    ports:
     - "<external>:443"
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    volumes:
      - heimdall:/config
    restart: unless-stopped

volumes:
  heimdall:
